sudo: required

language: cpp
os: osx
osx_image: xcode8

install:
 - cd ..
 - wget https://github.com/psavery/genXrdPattern/releases/download/temporary-tests/objcryst-o2-optimizations.tgz
 - tar -xzvf objcryst-o2-optimizations.tgz
 - objcryst_dir=$(pwd)/objcryst-o2-optimizations
 - echo "objcryst_dir is ${objcryst_dir}"
 - cd objcryst-o2-optimizations/Fox
 - export CXXFLAGS="-mmacosx-version-min=10.9 -O2"
 - export CPPFLAGS="-mmacosx-version-min=10.9 -O2"
 - export CFLAGS="-mmacosx-version-min=10.9 -O2"
 - export LDFLAGS="-mmacosx-version-min=10.9"
 - export CXX="g++"
 - make Fox-nogui shared=0
 - cd ../../genXrdPattern

script:
 - mkdir build
 - cd build
 - cmake .. -DObjCryst_ROOT=${objcryst_dir}
 - make
 - ./genXrdPattern

deploy:
  - provider: releases
    file:
      - genXrdPattern
    skip_cleanup: true
    api_key:
      secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
    on:
      repo: psavery/genXrdPattern
      all_branches: true
