sudo: required

language: cpp
os: osx
osx_image: xcode8

install:
 - cd ..
 - wget https://github.com/psavery/genXrdPattern/releases/download/temporary-tests/objcryst-o2-optimizations.tgz
 - tar -xzvf objcryst-o2-optimizations.tgz
 - objcryst_dir=$(pwd)/objcryst-o2-optimizations
 - echo "objcryst_dir is ${objcryst_dir}"
 - cd objcryst-o2-optimizations/Fox
 - export CXXFLAGS="-mmacosx-version-min=10.9 -O2"
 - export CPPFLAGS="-mmacosx-version-min=10.9 -O2"
 - export CFLAGS="-mmacosx-version-min=10.9 -O2"
 - export LDFLAGS="-mmacosx-version-min=10.9"
 - export CXX="g++"
 - make Fox-nogui shared=0
 - cd ../../genXrdPattern

script:
 - mkdir build
 - cd build
 - cmake .. -DObjCryst_ROOT=${objcryst_dir}
 - make
 - ./genXrdPattern || (exit 0)

deploy:
  - provider: releases
    file:
      - genXrdPattern
    skip_cleanup: true
    api_key:
      secure: WljyI7pTiA33cEr87u17brEOKCOwzPeZvro7CLrH5Mp3Pa9Yb388/CMUlMLeU1OPuYOyfCDImnNDAj784Ovb0kiSqRKzBc5dGI+ngE43W5OoRvOfRz33rUSHuBNFbBa/cPhGaRn3AfmurwaPm3G6sETjGxHDk/vyKwtjqMloyets4Yzrz1iSjKq1wj9VmzJidMG/S42gkQbM94RVmyXMzkWp1EJzZTYUzF0dygggKl162uDhJWsTChqHv3zutm/HueyyB5f18eer+pcR8X9MzI+Jv6epYc+BXPfP164a1bMloDCiP+NMx+MIQRUbsQt53h6ODuP1DsIxlh3XmiKc+knkcypbBPJNYARvP2dlWH/Ric//2L91p0p3wHoo7nuwzgNhEzVyhlrewqjTm+w5+7NJfgQGyGSHfxwoeBNXA2Yx/yIhD5rPFPaScTGrvw0yvSD9FTtbZN0GZcki9P04gveUIcCjwrcg14iwKK0DgM9d1IMJSFi4nk5P2OrS3r8o1LN8pIZuLqQK/P/oaOshuiXszMxjhh+/dfMRP6p8DtQvna6W9d/+1w5Rii6BPcG2fIm0uOSvxmoeobdPH7AzIlHIpRLMXWydY1RT16k7nME8V5mPFjeaQGXCIV+vMBF1x8djSLxc+5S60RxRWogZSjdYxmC9AZoIi7kUaC13s98=
    on:
      repo: psavery/genXrdPattern
      tags: true
      all_branches: true
